openapi: 3.0.0
info:
  title: Invoice App
  description: API
  version: 0.1.9

servers:
  - url: https://parking-app-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:3001/
    description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /signup:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User created successfully
        "401":
          description: User with this email already exists
